# Generated by Django 4.1.4 on 2023-01-05 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='note',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='note',
            name='folders',
            field=models.ManyToManyField(blank=True, related_name='note_folders', to='app.folder'),
        ),
        migrations.AddField(
            model_name='note',
            name='loved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='note',
            name='pinned',
            field=models.BooleanField(default=False),
        ),
    ]
