# Generated by Django 4.1.4 on 2023-01-16 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_note_options_alter_folder_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='co_authors',
        ),
    ]
