# Generated by Django 4.1.4 on 2023-01-21 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_note_co_authors'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='folder',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AddField(
            model_name='note',
            name='deleted_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
